jobs:
- name: unit-testing
  plan:
  - task: v1
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args: 
        - -c
        - |
          echo "Hello, world!"
